# Generated by Django 2.2.1 on 2019-10-06 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oglasivac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imePrezime', models.CharField(max_length=255)),
                ('tipOglasavanja', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('godinaPocetak', models.IntegerField()),
                ('mesecPocetak', models.IntegerField()),
                ('danPocetak', models.IntegerField()),
                ('godinaKraj', models.IntegerField()),
                ('mesecKraj', models.IntegerField()),
                ('danKraj', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RacunStanara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isPlatio', models.BooleanField(default=False)),
                ('napomena', models.CharField(max_length=255)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Period')),
            ],
        ),
        migrations.CreateModel(
            name='Zgrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulica', models.CharField(max_length=255)),
                ('broj', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stanar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezime', models.CharField(max_length=255)),
                ('broj', models.IntegerField()),
                ('mesecniIznos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('racunstanar', models.ManyToManyField(through='blog.RacunStanara', to='blog.Period')),
                ('zgrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Zgrada')),
            ],
        ),
        migrations.AddField(
            model_name='racunstanara',
            name='stanar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Stanar'),
        ),
    ]
