# Generated by Django 2.2.1 on 2019-10-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191006_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stanar',
            old_name='broj',
            new_name='brojStana',
        ),
    ]
