# Generated by Django 2.2.1 on 2019-10-06 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20191006_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='stanar',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='period',
            name='kraj',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='period',
            name='pocetak',
            field=models.DateField(),
        ),
    ]
