# Generated by Django 2.2.1 on 2019-10-06 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191006_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reklama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=255)),
                ('mesecniIznos', models.IntegerField()),
                ('oglasivac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Oglasivac')),
                ('zgrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Zgrada')),
            ],
        ),
        migrations.AddField(
            model_name='oglasivac',
            name='reklamaOglasivaca',
            field=models.ManyToManyField(through='blog.Reklama', to='blog.Zgrada'),
        ),
    ]
