# Generated by Django 2.2.1 on 2019-10-06 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191006_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='RacunReklama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iznos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isPlatio', models.BooleanField(default=False)),
                ('napomena', models.CharField(max_length=255)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Period')),
                ('reklama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Reklama')),
            ],
        ),
        migrations.AddField(
            model_name='reklama',
            name='racunReklam',
            field=models.ManyToManyField(through='blog.RacunReklama', to='blog.Period'),
        ),
    ]
