# Generated by Django 2.2.1 on 2019-10-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20191006_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='oglasivac',
            name='dugovanje',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stanar',
            name='dugovanje',
            field=models.IntegerField(default=0),
        ),
    ]
