# Generated by Django 2.1.15 on 2020-06-13 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_auto_20191006_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='anonymous.jpg', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='oglasivac',
            name='dugovanje',
            field=models.IntegerField(default=0, verbose_name='dugovanje (rsd)'),
        ),
        migrations.AlterField(
            model_name='racunreklama',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racunireklama', to='blog.Period'),
        ),
        migrations.AlterField(
            model_name='racunreklama',
            name='reklama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racunireklama', to='blog.Reklama'),
        ),
        migrations.AlterField(
            model_name='racunstanara',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racuni', to='blog.Period'),
        ),
        migrations.AlterField(
            model_name='racunstanara',
            name='stanar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racuni', to='blog.Stanar'),
        ),
        migrations.AlterField(
            model_name='reklama',
            name='oglasivac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reklame', to='blog.Oglasivac'),
        ),
        migrations.AlterField(
            model_name='reklama',
            name='zgrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reklame', to='blog.Zgrada'),
        ),
        migrations.AlterField(
            model_name='stanar',
            name='dugovanje',
            field=models.IntegerField(default=0, verbose_name='dugovanje (rsd)'),
        ),
        migrations.AlterField(
            model_name='stanar',
            name='zgrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stanari', to='blog.Zgrada'),
        ),
    ]
