# Generated by Django 2.1.15 on 2020-06-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200613_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='stanar',
            name='profile_pic',
            field=models.ImageField(blank=True, default='anonymous.jpg', null=True, upload_to=''),
        ),
    ]
