# Generated by Django 2.1.15 on 2020-06-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200614_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezultatitreptanja',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
